plugins {
    id "com.android.application"
}

android {
    namespace "com.example.eightwayime"
    compileSdk 35

    defaultConfig {
        applicationId "com.example.eightwayime"
        minSdk 21
        targetSdk 35
        versionCode 5
        versionName "0.2.3"
    }

    signingConfigs {
        release {
            storeFile file("${System.properties['user.home']}/.android/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
